name: Build and Push Docker Image to GHCR on Tag

on:
  push:
    tags:
      - 'v*' # Trigger only when a tag matching the pattern 'v*' is pushed (e.g., v1.0.0, v2.1.3)

env:
  DOCKER_IMAGE_NAME: jpdfsigner
  IMAGE_TAG: ${{ github.ref_name }} # Use the tag name as the image tag (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Add explicit permissions for GitHub Packages
    permissions:
      contents: read
      packages: write
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 3: Set up Docker Buildx for improved building capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ env.IMAGE_TAG }}