name: Java Tests

on:
  push:
  pull_request:

permissions: write-all

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: amazoncorretto:21

    steps:
      # Install Git, wget, tar, and other dependencies
      - name: Install Git, wget, and tar
        run: |
          yum update -y
          yum install -y git wget tar
          git --version
          wget --version
          tar --version
          
      # Manual checkout using Git
      - name: Manual checkout
        run: |
          # Configure Git to handle the directory safely
          git config --global --add safe.directory /__w/jpdfsigner/jpdfsigner
          
          # Create a fresh directory and clone into it
          mkdir -p /tmp/repo
          cd /tmp/repo
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git .
          
          # Copy the files to the workspace
          cp -r * /__w/jpdfsigner/jpdfsigner/
          cd /__w/jpdfsigner/jpdfsigner/
          
          # Debug info
          ls -la
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Install a specific version of Maven
      - name: Install Maven
        run: |
          # Install Maven 3.8.8
          MAVEN_VERSION=3.8.8
          wget https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz -C /usr/local/
          ln -s /usr/local/apache-maven-$MAVEN_VERSION/bin/mvn /usr/local/bin/mvn
          
          # Verify installation
          mvn --version

      # Run the tests with Maven
      - name: Build and test with Maven
        run: mvn -B test
        
      # Display test results in the console
      - name: Print test summary
        if: always()
        run: |
          echo "=== TEST RESULTS ==="
          if [ -d "target/surefire-reports" ]; then
            for report in target/surefire-reports/*.txt; do
              echo "--- $report ---"
              cat "$report"
              echo
            done
          else
            echo "No test reports found."
          fi